### ISSUE TITLE
Support for cypress component testing?

### ISSUE THREAD

**Issue by sdaconceicao** [mfrachet/cypress-audit#117]
I'm attempting to use audit to test out a11y and performance issues via cypress component testing, but as far as I can tell this currently isn't possible. With @cypress/react, instead of visiting a url you just mount a component which gets loaded into the browser. When trying to run cy.lighthouse on this mounted component, the blank page appears in the browser for about 10 seconds before all of the tests fail with 0 out of 100 results.
Is there anyway to have lighthouse run on these mounted components?

**Comment by mfrachet** [comment]
lighthouse needs a specific URL to work. I don't know how easy/hard it would be to extract the URL where the component is spawned 🤔 .

Will give it a try

**Comment by rswerve** [comment]
>lighthouse needs a specific URL to work
Is this also true of pa11y?  We'd like to run the pa11y check with a page in various states (load URL, interact with the page, then run pa11y).  Is that possible?

**Comment by mfrachet** [comment]
Yes, pa11y needs a URL too. From its documentation: https://github.com/pa11y/pa11y#pa11y

**Comment by mfrachet** [comment]
Okay, after investigations, it's not possible _for now_ to make the lib work with component testing. The reason is that Cypress sets a variable called `Cypress` on the `window` object **in the tab where the test runs**. When lighthouse opens the new tab, the Cypress global does not exist in it and the component can't mount.

One solution could be to transfer the cypress object between the tabs, but I don't know how to do that. Another solution would be to make sure Cypress injects the global on every tabs on its browser 🤷🏻

**Comment by mfrachet** [comment]
Closing this for now since it will probably not happen before a very long time. Feel free to reopen later if necessary 😊
