### ISSUE TITLE
Lighthouse CI

### ISSUE THREAD

**Issue by mxkyb** [mfrachet/cypress-audit#128]
I'd like to clarify because I couldn't find information about this in the documentation or other issues, it is not possible to use this plugin together with [lighthouse-ci](https://github.com/GoogleChrome/lighthouse-ci), right?

My use cases are:
- run lighthouse multiple times to collect median values to decrease fluctuation
- upload results to an lhci server

**Comment by mfrachet** [comment]
From what I understand of lhci, it may be possible to send the reports to the server and have the visualization 🤔 . I have to investigate I think :D

**Comment by mfrachet** [comment]
After investigating, you can't use both `$ lhci autorun` and cypress audit. However, since cypress-audit provides the raw report (https://github.com/mfrachet/cypress-audit/blob/master/packages/lighthouse/README.md#accessing-the-raw-reports) it might be possible to upload it on a lhci server and track the changes over time :) 

I don't have the implementation details, what you would have to do is to find a way to upload the report at the good format.

**Comment by mxkyb** [comment]
Thanks for the clarification! :)
