### ISSUE TITLE
security vulnerabilities on xmldom package

### ISSUE THREAD

**Issue by poponuts** [mfrachet/cypress-audit#72]
npm audit reveals the following:
───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Misinterpretation of malicious XML input                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ xmldom                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.5.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cypress-audit [dev]                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cypress-audit > lighthouse > jsonld > xmldom                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1650                            │

**Comment by pakhilov** [comment]
xmldom  <0.5.0
Misinterpretation of malicious XML input - https://npmjs.com/advisories/1650
No fix available
node_modules/xmldom
  jsonld  0.0.59 - 3.3.2
  Depends on vulnerable versions of xmldom
  node_modules/jsonld
    lighthouse  >=4.3.0
    Depends on vulnerable versions of jsonld
    node_modules/lighthouse
      cypress-audit  *
      Depends on vulnerable versions of lighthouse
      node_modules/cypress-audit

4 low severity vulnerabilities

I have the same critical problem!

**Comment by mfrachet** [comment]
Unfortunately, I can't do anything on this one since it's a problem introduced by a transitive dependency of lighthouse called "jsonld". I suggest you refer to these projects in case this is a blocker for you since I can't do anything about that for now :)

<img width="924" alt="Screenshot 2021-03-18 at 09 33 11" src="https://user-images.githubusercontent.com/3874873/111596048-095bf900-87cd-11eb-9e5d-8d17ef841039.png">

I'm closing this but feel free to continue the discussion 😊
