### ISSUE TITLE
Is this possible to use cy.lighthouse() with a mocked api?

### ISSUE THREAD

**Issue by Renaud009** [mfrachet/cypress-audit#81]
When triggering lighthouse in my test... my mocked apis defined in cypress seems completely ignored in favor of 404 errors. The report is generated but I can see in the tab opened for lighthouse that something is wrong since I see error popups. My "fake login information" in the session storage seems to be passed along the lighthouse tab tho.

Note that all my apis are mocked so any ideas on how to resolve this?

**Comment by mfrachet** [comment]
Do you have a repro example so that I can play with it?

To give a bit more information, this library allows to:

- run the lighthouse module verifications **against the cypress browser**
- in order to run tests on authenticated pages, **we keep the session storage and never clean it up**

However, the module is not supposed to impact your requests mocking

**Comment by mfrachet** [comment]
I'm closing this issue for now. Feel free to reopen if necessary 😊
