### ISSUE TITLE
The plugin should  be able to log  more specifically threshold using lighthouse

### ISSUE THREAD

**Issue by appedro** [mfrachet/cypress-audit#97]
In one of my projects, we have differents values with prod/dev project when using lighthouse. But we couldn't identify the reason for the number be lower when testing in prod. It should be able to get more descriptive infos, so we can fix it.

**Comment by mfrachet** [comment]
As mentioned in https://github.com/mfrachet/cypress-audit/issues/89 , lighthouse scores vary depending on the machine, the network and a lot of other factors.

There's also a config tweak to stick as much as possible to the lighthouse cli config. I don't have that much control here since I'm just bridging lighthouse and cypress, without any extra config (except keeping the cache).

I'm closing, feel free to continue on https://github.com/mfrachet/cypress-audit/issues/89
